<a href="https://colab.research.google.com/github/jang-jinyeol/Machine_Learning/blob/main/Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

import numpy as np
import pandas as pd

In [ ]:
iris_data = load_iris()

In [ ]:
print("iris_dataset의 키: \n{}".format(iris_data.keys()))

iris_dataset의 키: 
dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [ ]:
print(iris_data['DESCR'][:193] + "\n....")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, pre
....


In [ ]:
print("타깃의 이름: {}".format(iris_data['target_names']))

타깃의 이름: ['setosa' 'versicolor' 'virginica']


In [ ]:
print("특성의 이름: \n{}".format(iris_data['feature_names']))

특성의 이름: 
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [ ]:
print("data의 타입: {}".format(type(iris_data['data'])))

data의 타입: <class 'numpy.ndarray'>


In [ ]:
print("data의 크기: {}".format(iris_data['data'].shape))
#행은 개개의 꽃, 열은 각 꽃에서 구한 네 개의 측정치

data의 크기: (150, 4)


In [ ]:
print("data의 처음 다섯 행:\n{}".format(iris_data['data'][:5]))
#다섯 붓꽃의 꽃잎 폭은 모두 0.2cm이고, 첫 번째 꽃이 가장 긴 5.1cm의 꽃받침을 가졌다

data의 처음 다섯 행:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [ ]:
print("target의 타입: {}".format(type(iris_data['target'])))

target의 타입: <class 'numpy.ndarray'>


In [ ]:
print("target의 크기: {}".format(iris_data['target'].shape))
#target은 1차원 배열

target의 크기: (150,)


In [ ]:
print("타깃:\n{}".format(iris_data['target']))

타깃:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris_data['data'],iris_data['target'], random_state=0)

In [ ]:
print("X_train 크기: {}".format(X_train.shape))
print("y_train 크기: {}".format(y_train.shape))

X_train 크기: (112, 4)
y_train 크기: (112,)


In [ ]:
print("X_train 크기: {}".format(X_test.shape))
print("y_train 크기: {}".format(y_test.shape))

X_train 크기: (38, 4)
y_train 크기: (38,)


In [ ]:
#KNeighborsClassifier 클래스로 부터 객체 생성과정, 이웃의 개수는 1로 설정.
#k-Nearest Neighbors, k-NN
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

In [ ]:
#fit 메서드를 사용하여 훈련 데이터셋으로부터 모델을 만든다.
#인자는 NumPy 배열 X_train과 훈련 데이터의 레이블을 담고 있는 NumPy 배열 y_train 이다.
#fit 메서드는 knn 객체 자체를 반환한다.(knn 객체 자체를 변경시킴)
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [ ]:
#예측하기
#붓꽃 하나의 측정값은 2차원 NumPy 배열에 행으로 들어간다.
#scikit-learn은 항상 데이터가 2차원 배열일 것으로 예상한다.
X_new = np.array([[5, 2.9, 1, 0.2]])
print("X_new.shape: {}".format(X_new.shape))

X_new.shape: (1, 4)


In [ ]:
prediction = knn.predict(X_new)
print("예측: {}".format(prediction))
print("예측한 타깃의 이름: {}".format(iris_data['target_names'][prediction]))

예측: [0]
예측한 타깃의 이름: ['setosa']


In [ ]:
#모델 평가하기
#한번도 사용 안 한 X_test 이용
y_pred = knn.predict(X_test)
print("테스트 세트에 대한 예측값:\n {}".format(y_pred))
##### 다시 볼 것 ! ####
print("테스트 세트의 정확도: {:.2f}".format(np.mean(y_pred == y_test)))
##### 다시 볼 것 ! ####
print("테스트 세트의 정확도: {:.2f}".format(knn.score(X_test, y_test)))

테스트 세트에 대한 예측값:
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]
테스트 세트의 정확도: 0.97
테스트 세트의 정확도: 0.97
